name: "git-config"
author: "Marco Ieni"
description: "Configure the git user corresponding to the `GITHUB_TOKEN` environment variable."
branding:
  icon: "zap"
  color: "yellow"
runs:
  using: "composite"
  steps:
    - id: commit-author
      name: Determine Git user info from GitHub token
      shell: bash
      run: |
        # The environment variable GITHUB_TOKEN is read by the `gh` cli
        VIEWER_JSON=$(gh api graphql -f query='query { viewer { name login databaseId }}' --jq '.data.viewer')
        VIEWER_NAME=$(jq --raw-output '.name | values' <<< "${VIEWER_JSON}")
        VIEWER_LOGIN=$(jq --raw-output '.login' <<< "${VIEWER_JSON}")
        VIEWER_DATABASE_ID=$(jq --raw-output '.databaseId' <<< "${VIEWER_JSON}")

        USER_NAME="${VIEWER_NAME:-${VIEWER_LOGIN}}"

        USER_EMAIL="${VIEWER_DATABASE_ID}+${VIEWER_LOGIN}@users.noreply.github.com"

        git config --global user.name ${USER_NAME}
        git config --global user.email ${USER_EMAIL}

        echo "name=${USER_NAME}" >> "${GITHUB_OUTPUT}"
        echo "email=${USER_EMAIL}" >> "${GITHUB_OUTPUT}"
